---
title: "RostL_project_code.Rmd"
author: "Lauren Rost"
date: "4/21/2019"
output: pdf_document
---


```{r}
dat <- fread("final_data.csv") %>% as_tibble()
```

# Maybe we should treat instance as a x to train on, and not consolidate all people into one line. Might be more informative to time data.

# Using od_type as outcome 
# could also use total_da


# For survival analysis,
# should we do the number of years since being admitted in the system? to allow us to look at more than just the 2009 cohort?
```{r}
# Multivariate logistic regression

# 50-50 split
dat_scrambled <- dat[sample(1:nrow(dat)),]
dat_train <- dat_scrambled[1:(dim(dat_scrambled)[1]/2),]
dat_test <- dat_scrambled[-(1:(dim(dat_scrambled)[1]/2)),]

dat_binary_odtype <- dat
dat_binary_odtype$od_type[which(dat_binary_odtype$od_type=="No Overdose")] <- 0
dat_binary_odtype$od_type[which(dat_binary_odtype$od_type=="Non-Opiate Overdose")] <- 0
dat_binary_odtype$od_type[which(dat_binary_odtype$od_type=="Opiate Overdose")] <- 1


# Predicting "Opiate Overdose" vs. no overdose or non-opiate overdose based on total_cr_drug_cases
lr = with(dat_train, glm(od_type=="Opiate Overdose" ~ total_cr_drug_cases, family = binomial("logit")))  
lr %>% summary()    # estimates are the data coefficients; intercept = B0; each after is a B for the dummy variable; stars give the level of significance of the coefficients; all values are compared to a reference value (b was the reference value here); "values" can also be called "indicator values"; extract the Beta-hats
lr %>% str()
lr %>% summary() %>% coef()
predictions = data.frame(preds=(lr %>% predict(dat_test, type="response"))) # get predictions on new data; "response" gives predicted probabilities
library(ggplot2)
dat_test %>%
  select(od_type) %>%
  bind_cols(predictions) %>%
  table() %>%
  data.frame() %>% as_tibble() %>%
  group_by(preds) %>%
  mutate(testfreq = sum(Freq)) %>%
  mutate(testfreq = Freq/testfreq) %>%
  ungroup() %>% filter(od_type=='Opiate Overdose') %>%
  select(preds,testfreq) %>%   # this model is relatively well-calibrated; if predictions perfectly calibrated, y=x
  mutate_all(as.character) %>%
  mutate_all(as.numeric) %>%
  ggplot(data=., aes(x=preds, y=testfreq)) + geom_point() + geom_abline(slope=1)

```

```{r}
library(ROCR)
columns_for_ROC =  # columns: predictions, labels
  dat_test %>%
  select(od_type) %>%
  bind_cols(predictions) %>% mutate(od_type=od_type=="Opiate Overdose")   # true labels, and their predictions

# plot it:
prediction(predictions=columns_for_ROC$preds,
           labels=columns_for_ROC$od_type) %>%
  performance("tpr", "fpr") %>% plot()
  # performance("auc")  # swap out to get AUC

```

```{r}
# Regularized multivariate logistic regression (lasso)
# Jumping-off point from Dr. Weiss' example to work off of:

# library(glmnet)
# library(tidyr)
# mushmm = model.matrix(type~., mush[,-17]) # turns categorical vars into indicators
# mushmmtrain = mushmm[1:5000,]
# mushmmtest = mushmm[-(1:5000),]
# lr1 = glmnet(x = mushmmtrain, y=mushtrain$type, family="binomial")
# str(lr1)
# which(coef(lr1)[,20] > 0)
# which(coef(lr1)[,10] > 0)
# 
# data.frame(preds = lr1 %>% predict(mushmmtest, s=0.2, type="response"),
#            y = mushtest$type) %>% tbl_df() %>%
#   table() %>% data.frame() %>% tbl_df() %>%
#   transmute(type=y, preds=X1, Freq=Freq)%>%
#   arrange(preds) %>%
#   group_by(preds) %>%
#   mutate(testfreq = sum(Freq)) %>%
#   mutate(testfreq = Freq/testfreq) %>% 
#   ungroup() %>%
#   filter(type=='p') %>%
#   select(preds,testfreq)


```


```{r}
# Random forest
library(randomForest)
dat_scrambled <- as_tibble(dat_scrambled)

# NAs introduced by coercion; col 14, 15, 16 (119428)

data_fac <- dat_binary_odtype %>% mutate_if(is.character, as.factor)

forest = randomForest(formula = as.factor(data_fac$od_type) ~ .,
                      data=data_fac[, -c(14:16)] %>% filter(!is.na(od_type)))
forest$importance
library(ggplot2)
ggplot(data=forest$importance %>% as.data.frame() %>%
         mutate(name=as.factor(rownames(.))) %>%
         arrange(MeanDecreaseGini) %>%
         mutate(name=factor(name, name))) +
  geom_bar(aes(x=name, y=MeanDecreaseGini), stat="identity") + coord_flip()
predict(forest, data_fac, type = "prob") %>% hist(breaks=100) # %>% head()

```


```{r}
# Boosting
library(ada)
aforest = ada(formula = od_type ~ .,
              data=data_fac[-c(14:16)] %>% filter(!is.na(od_type)),
              iter=10)
predict(aforest, data_fac[,-c(14:16)],
        type = "probs") %>% hist(breaks=100) # %>% head()

```

```{r}
# Gradient boosting machine
library(gbm)
gforest = gbm(formula = od_type==1 ~ .,
              data=data_fac %>% filter(!is.na(od_type)) %>%
                mutate_if(is.logical, as.factor),
              interaction.depth=10,
              cv.folds = 2)
predict(gforest, data_fac %>% mutate_if(is.logical, as.factor),
        n.trees=gforest$n.trees,
        type = "response") %>% hist(breaks=100)  # %>% head()

```

```{r}
# K-means clustering

``` 


