---
title: "ML Pipeline Project Code"
author: "Lauren Rost, Mridul Singh Gangawar, Nikita Setia"
date: "March 19, 2019"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
#--- Loading helper files 
loadlibs = function(libs) {
  for(lib in libs) {
    class(lib)
    if(!do.call(require,as.list(lib))) {install.packages(lib)}
    do.call(require,as.list(lib))
  }
}
libs = c("tidyr","magrittr","purrr","dplyr","stringr","readr","data.table", "mice", 
         "randomForest", "ada", "gbm", "caret", "e1071", "ROCR", "ggplot2", "glmnet", "readxl",
         "survival", "fastDummies", "DataExplorer", "ggplot2", "corrplot")

library(data.table)
loadlibs(libs)

mode_fun <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

#--- setting global decimal print setting
options(scipen=4)
source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")

prog = fread("program_activity.csv") %>% as_tibble() 
dem = fread("demographic.csv") %>% as_tibble() 
presc = fread("opiate_prescription_fills.csv") %>% as_tibble()

```

```{r}

summary(dem %>% mutate_if(is.character, as.factor))

# missing data for RACE and GENDER
# merging native hawaiian/pacific islander + no data = no data and other because the former is too small
# merging transgendered male to female and no data = no data and other because former is too small
# dealing with missingness by allowing it to be its own category - because most likely MNAR
```

```{r}

dem$RACE[which(grepl("No Data", dem$RACE))] = "No Data and Other"
dem$RACE[which(grepl("Native Hawaiian", dem$RACE))] = "No Data and Other"
dem$GENDER[which(grepl("No Data", dem$GENDER))] = "No Data and Other"
dem$GENDER[which(grepl("Transgendered", dem$GENDER))] = "No Data and Other"

dem = dem %>% rename("race"=RACE, "gender"=GENDER)
summary(dem %>% mutate_if(is.character, as.factor))
```


```{r}

summary(prog)

# No missing values in the program data 
# Overdose date and opiate overdose has NAs for individuals who have not overdosed, 
# so that is meaningful and not actually missing

```

```{r}

prog = prog %>% separate(OVERDOSE_DATE, c("OVERDOSE_YEAR", "OVERDOSE_MONTH"), remove=FALSE, sep=4)

prog$OPIATE_OVERDOSE[which(grepl(0, prog$OPIATE_OVERDOSE))] = "Non-Opiate Overdose"
prog$OPIATE_OVERDOSE[which(grepl(1, prog$OPIATE_OVERDOSE))] = "Opiate Overdose"
prog$OPIATE_OVERDOSE[which(is.na(prog$OPIATE_OVERDOSE))] = "No Overdose"

summary(prog %>% mutate_if(is.character, as.factor))


```

```{r}

times_used = prog %>% group_by(PERSON_ID) %>% select(YEAR, MONTH) %>% summarise(times_used = max(sequence(n())))

prog_summary = prog %>% group_by(PERSON_ID) %>% summarise(total_cyfchild = sum(CYFCHILD),
                                                          total_cyfparent = sum(CYFPARENT),
                                                          total_mh = sum(MH),
                                                          total_da = sum(DA),
                                                          total_rx = sum(RX),
                                                          total_acj = sum(ACJ),
                                                          total_cr_cases = sum(MDJS_CR_CASES),
                                                          total_cr_drug_cases = sum(MDJS_CR_DRUG_CASES),
                                                          cohort = min(YEAR),
                                                          od_date = max(OVERDOSE_DATE), 
                                                          od_year = max(OVERDOSE_YEAR), 
                                                          od_month = max(OVERDOSE_MONTH), 
                                                          od_type = max(OPIATE_OVERDOSE))
```


```{r}

summary(presc %>% mutate_if(is.character, as.factor))

```

```{r}

age_df = presc %>% group_by(PERSON_ID) %>% summarise(min_age = min(AGE), max_age = max(AGE), mean_age = round(mean(AGE)))

age_df = age_df %>% group_by(PERSON_ID) %>% mutate(age_clean = if_else(min_age<0, max_age, min_age)) %>%
  mutate(age_clean = if_else(age_clean<0, 999, age_clean))

age_df$age_clean[which(age_df$age_clean>99)] = NA
age_df$age = age_df$age_clean
age_df$age[which(is.na(age_df$age_clean))] = median(age_df$age_clean, na.rm=TRUE)

summary(age_df)
```

```{r}

presc$drug_strength <- str_extract(presc$LABEL_NAME, "[0-9].*")

# drug strength indicated that these are oral solutions per 5ML, so made this change manually
presc$drug_strength[which(grepl('ORAL SOLUTION', presc$extract_strength))] <- "5-325/5ML"
presc$drug_strength[which(grepl('NALOXONE', presc$LABEL_NAME))] <- "50MG-0.5MG"
presc = presc %>% mutate(drug_strength = if_else(is.na(drug_strength), DRUG_STRENGTH, drug_strength))

# Creating a new column 'num_strength' that keeps only numeric values from 'drug_strength'
presc$num_strength <- str_extract(presc$drug_strength, "[0-9]*.*[0-9]")

presc <- separate(presc, num_strength, c("opioid_strength", "compound_strength"), sep = '-')
presc <- separate(presc, opioid_strength, c("opioid", "divisor"), sep = '/')
presc$opioid <- str_extract(presc$opioid, "[0-9]*.*[0-9]")
presc <- separate(presc, compound_strength, c("compound", "divisor2"), sep = '/')
#sum(presc$divisor==presc$divisor2,na.rm=TRUE)
presc = presc %>% mutate(divisor = if_else(is.na(divisor), divisor2, divisor))
presc = presc %>% select(-divisor2)
presc = presc %>% mutate(opioid = if_else(is.na(compound), opioid, 
                                                  if_else(opioid>compound, compound, opioid)))
presc$divisor[which(is.na(presc$divisor))] = 1
presc$compound[which(is.na(presc$compound))] = 1

presc = presc %>% mutate(opioid_converted = as.numeric(opioid)/as.numeric(divisor))

```

```{r}

presc <- presc %>% 
  mutate(conversion_factor = 
    if_else(grepl('BUPRENORPHINE', GENERIC_NAME) & grepl('PATCH', DOSAGE_FORM_DESC), 12.6, 
    if_else(grepl('BUPRENORPHINE', GENERIC_NAME) & grepl('AMPUL', DOSAGE_FORM_DESC), 30,
    if_else(grepl('BUTORPHANOL', GENERIC_NAME), 7,
    if_else(grepl('CODEINE', GENERIC_NAME), 0.15,
    if_else(grepl('DIHYDROCODEINE BITARTRATE', GENERIC_NAME), 0.25,
    if_else(grepl('OPIUM', GENERIC_NAME), 1,
    if_else(grepl('FENTANYL', GENERIC_NAME) & grepl('TABLET', DOSAGE_FORM_DESC), 0.13,
    if_else(grepl('FENTANYL', GENERIC_NAME) & grepl('LOZENGE', DOSAGE_FORM_DESC), 0.13,
    if_else(grepl('FENTANYL', GENERIC_NAME) & grepl('PATCH', DOSAGE_FORM_DESC), 7.2,
    if_else(grepl('NALBUPHINE', GENERIC_NAME), 1,
    if_else(grepl('FENTANYL CITRATE', GENERIC_NAME), 0.13,
    if_else(grepl('HYDROCODONE', GENERIC_NAME), 1,
    if_else(grepl('HYDROMORPHONE', GENERIC_NAME), 4,
    if_else(grepl('LEVORPHANOL TARTRATE', GENERIC_NAME), 11,
    if_else(grepl('MEPERIDINE', GENERIC_NAME), 0.1,
    if_else(grepl('METHADONE', GENERIC_NAME) & opioid_converted<=20, 4, 
    if_else(grepl('METHADONE', GENERIC_NAME) & opioid_converted>20, 8, 
    if_else(grepl('MORPHINE', GENERIC_NAME), 1, 
    if_else(grepl('OXYCODONE', GENERIC_NAME), 1.5, 
    if_else(grepl('OXYMORPHONE', GENERIC_NAME), 3,
    if_else(grepl('PENTAZOCINE', GENERIC_NAME), 0.37,
    if_else(grepl('TAPENTADOL', GENERIC_NAME), 0.4,
    if_else(grepl('TRAMADOL', GENERIC_NAME), 0.1, 0))))))))))))))))))))))))

```


```{r}

#presc %>% group_by(generic_name) %>% summarise(count = n()) %>% arrange(count)
presc <- presc %>% 
  mutate(generic_name = 
    if_else(grepl('DIHYDROCODEINE BITARTR', presc$GENERIC_NAME), 'DIHYDROCODEINE BITARTRATE', 
    if_else(grepl('BUPRENORPHINE', presc$GENERIC_NAME), 'BUPRENORPHINE',
    if_else(grepl('HYDROCODONE BITARTRAT', presc$GENERIC_NAME), 'HYDROCODONE BITARTRATE',
    if_else(grepl('MORPHINE SULFATE', presc$GENERIC_NAME), 'MORPHINE SULFATE',
    if_else(grepl('OXYCODONE', presc$GENERIC_NAME), 'OXYCODONE', 
    if_else(grepl('PENTAZOCINE', presc$GENERIC_NAME), 'PENTAZOCINE',
    if_else(grepl('TRAMADOL', presc$GENERIC_NAME), 'TRAMADOL',
    if_else(grepl('CODEINE PHOSPHATE', presc$GENERIC_NAME), 'CODEINE PHOSPHATE',
    if_else(grepl('OPIUM/BELLADONNA', presc$GENERIC_NAME), 'OPIUM/BELLADONNA', 
    if_else(grepl('FENTANYL', presc$GENERIC_NAME), 'FENTANYL',
    if_else(grepl('HYDROMORPHONE', presc$GENERIC_NAME), 'HYDROMORPHONE', 
    if_else(grepl('MEPERIDINE', presc$GENERIC_NAME), 'MEPERIDINE', GENERIC_NAME
    )))))))))))))


presc <- presc %>% 
  mutate(dosage_form = 
    if_else(grepl('TABLET', presc$DOSAGE_FORM_DESC), 'PILL', 
    if_else(grepl('VIAL', presc$DOSAGE_FORM_DESC), 'VIAL',
    if_else(grepl('SYRINGE', presc$DOSAGE_FORM_DESC), 'VIAL',
    if_else(grepl('CAPSULE', presc$DOSAGE_FORM_DESC), 'PILL', 
    if_else(grepl('PATCH', presc$DOSAGE_FORM_DESC), 'PATCH',
    if_else(grepl('LOZENGE', presc$DOSAGE_FORM_DESC), 'LOZENGE',
    if_else(grepl('AMPUL', presc$DOSAGE_FORM_DESC), 'AMPUL',
    if_else(grepl('SPRAY', presc$DOSAGE_FORM_DESC), 'SPRAY',
    if_else(grepl('SOLUTION', presc$DOSAGE_FORM_DESC), 'LIQUID',
    if_else(grepl('LIQUID', presc$DOSAGE_FORM_DESC), 'LIQUID',
    if_else(grepl('CONCENTRATE', presc$DOSAGE_FORM_DESC), 'LIQUID',
    if_else(grepl('SUPPOSITORY', presc$DOSAGE_FORM_DESC), 'SUPPOSITORY', 'NA'
    )))))))))))))
```

```{r}

# FIXING DAYS SUPPLY
loop_values = presc %>% group_by(generic_name, dosage_form) %>% summarise(count = n())

generics = loop_values[[1]]
dosages = loop_values[[2]]

min_supply_vec=rep(0, length(generics))
max_supply_vec=rep(0, length(generics))
min_dispensed_vec=rep(0, length(generics))
max_dispensed_vec=rep(0, length(generics))

for (i in 1:length(generics)){
  presc_subset = presc %>% filter(generic_name==generics[i] & dosage_form==dosages[i])
  min_supply_vec[i]=round(quantile(presc_subset$DAYS_SUPPLY , probs=seq(0, 1, by=0.005))[[2]])
  max_supply_vec[i]=round(quantile(presc_subset$DAYS_SUPPLY, probs=seq(0, 1, by=0.005))[[200]])
  
  min_dispensed_vec[i]=round(quantile(presc_subset$DISPENSED_QTY , probs=seq(0, 1, by=0.005))[[5]])
  max_dispensed_vec[i]=round(quantile(presc_subset$DISPENSED_QTY, probs=seq(0, 1, by=0.005))[[195]])
}

min_supply_vec = min_supply_vec %>% as.data.frame()
min_supply_vec = min_supply_vec %>% rename(min_supply_val = ".")
max_supply_vec = max_supply_vec %>% as.data.frame()
max_supply_vec = max_supply_vec %>% rename(max_supply_val = ".")

min_dispensed_vec = min_dispensed_vec %>% as.data.frame()
min_dispensed_vec = min_dispensed_vec %>% rename(min_dispensed_val = ".")
max_dispensed_vec = max_dispensed_vec %>% as.data.frame()
max_dispensed_vec = max_dispensed_vec %>% rename(max_dispensed_val = ".")

values = bind_cols(loop_values, min_supply_vec)
values = bind_cols(values, max_supply_vec)
values = bind_cols(values, min_dispensed_vec)
values = bind_cols(values, max_dispensed_vec)
values = values %>% select(-count)

presc = merge(presc, values, all.x = TRUE, key=c("generic_name, dosage_form"))

presc = presc %>% mutate(days_supply = if_else(DAYS_SUPPLY<min_supply_val, as.integer(min_supply_val), 
                                           if_else(DAYS_SUPPLY>max_supply_val, as.integer(max_supply_val),
                                                   as.integer(DAYS_SUPPLY))))

presc = presc %>% mutate(dispensed_qty = if_else(DISPENSED_QTY<min_dispensed_val,
                                                       as.integer(min_dispensed_val), 
                                           if_else(DISPENSED_QTY>max_dispensed_val, 
                                                   as.integer(max_dispensed_val),
                                                   as.integer(DISPENSED_QTY))))

```


```{r}

#unique(presc$conversion_factor)

presc$mme <- round((presc$opioid_converted*presc$dispensed_qty*presc$conversion_factor)/presc$days_supply,2)

# quantile(presc$mme, probs=seq(0, 1, by=0.005))
```



```{r, warning=FALSE, message=FALSE}

presc_summary = presc %>% group_by(PERSON_ID) %>% summarise(num_presc = n(), 
                                            most_presc_drug = mode_fun(generic_name),
                                            oxy_count = sum(grepl('OXYCODONE', generic_name)),
                                            tram_count = sum(grepl('TRAMADOL', generic_name)),
                                            hydrobit_count = sum(grepl('HYDROCODONE BITARTRATE', generic_name)),
                                            most_dose_form = mode_fun(dosage_form),
                                            pill_count = sum(grepl('PILL', dosage_form)),
                                            patch_count = sum(grepl('PATCH', dosage_form)),
                                            liquid_count = sum(grepl('LIQUID', dosage_form)),
                                            avg_mme = round(mean(mme)),
                                            median_mme = round(median(mme)),
                                            mode_mme = round(mode_fun(mme)),
                                            avg_supply = round(mean(days_supply)),
                                            avg_dispensed = round(mean(dispensed_qty)))

final_data = merge(dem, age_df %>% select(PERSON_ID, age), all.x = TRUE, all.y = TRUE, key="PERSON_ID")
final_data = merge(final_data, prog_summary, all.x = TRUE, all.y = TRUE, key="PERSON_ID")
final_data = merge(final_data, presc_summary, all.x = TRUE, all.y = TRUE, key="PERSON_ID")

summary(final_data %>% mutate_if(is.character, as.factor))

```

```{r}

write.csv(final_data, "final_data.csv", row.names = FALSE)


```

### Survival Analysis

```{r 2009 Cohort}

#most overdoses occur in the 2009 cohort, so makes sense to examine this one
#prog %>% group_by(cohort) %>% summarise(od = sum(OPIATE_OVERDOSE!="No Overdose"))

prog = prog %>% group_by(PERSON_ID) %>% mutate(cohort=min(YEAR))
prog_cohort2009 = prog %>% filter(cohort==2009)

paste("There are", length(unique(prog_cohort2009$PERSON_ID)), "individuals in the 2009 Cohort")

prog_cohort2009$year_month <- (as.integer(prog_cohort2009$YEAR)%%2009)*12+as.integer(prog_cohort2009$MONTH)

prog_cohort2009$od_year_month <- (as.integer(prog_cohort2009$OVERDOSE_YEAR)%%2009)*12+as.integer(prog_cohort2009$OVERDOSE_MONTH)

prog_cohort2009 = prog_cohort2009 %>% group_by(PERSON_ID) %>% mutate(min_yearmonth=min(year_month))
#prog_cohort2009 = prog_cohort2009 %>% filter(min_yearmonth==1)

survival_data = prog_cohort2009 %>% group_by(PERSON_ID) %>% summarise(time_yearmonth = max(year_month), 
                                                      od_time = max(od_year_month))
survival_data = survival_data %>% mutate(status = if_else(is.na(od_time), 0, 1))
survival_data = survival_data %>% mutate(time = if_else(is.na(od_time), time_yearmonth, od_time))
survival_data = survival_data %>% select(PERSON_ID, status, time)
survival_data = merge(survival_data, dem, key="PERSON_ID")
survival_data = merge(survival_data, age_df %>% select(PERSON_ID, age), key="PERSON_ID")

#plot 1
km = Surv(survival_data$time, survival_data$status) %>%
  (function(x) survfit(x ~ 1, data=survival_data))(.)
# Kaplan-Meier curve
plot(km, xlab= "Months",ylab="P(survive)", mark.time=T)
km

#plot 2 (by gender)
km_gender = survfit(Surv(survival_data$time, survival_data$status) ~ gender, data=survival_data)
plot(km_gender,
     col=c(1:3), mark.time = T); legend("bottomleft", c("Female","Male", "No Data & Other"), col=1:3, lty=c(1,1))
km_gender

#analysis by age
km_age = survfit(Surv(survival_data$time, survival_data$status) ~ age<45, data=survival_data)
km_age

#didn't make sense to plot this.. so just showing output
km_race = survfit(Surv(survival_data$time, survival_data$status) ~ race, data=survival_data)
km_race

```

```{r 2009 cohort cox}

### Cox model
cm = Surv(survival_data$time, survival_data$status) %>%
  (function(x) coxph(x ~ age + gender, data=survival_data))(.)
cm

#for 2009 cohort, being male increases hazard (coefficient)
#for 2009 cohort, men have 77% greater hazard compared to women??
#this is a statistically significant difference

#controlling for gender, age increases hazard (coefficient)
#1 year increase in age increases hazard by 2.6% controlling for gender??
#this is statistically significant and makes sense

### Regularized Cox model
cox_data = survival_data %>% select(-time, -status, -PERSON_ID) %>% as.data.frame() %>% as.matrix()
cox_data = cox_data %>% dummy_cols(c("gender", "race"))
cox_data = cox_data %>% select(-gender, -race) %>% as.data.frame() %>% as.matrix()

lm = glmnet(cox_data, Surv(survival_data$time, survival_data$status), family="cox")
plot(lm)

#How to choose s? Consider sparsity you want with cross-validation
cvlm = cv.glmnet(cox_data, Surv(survival_data$time, survival_data$status), family="cox")
plot(cvlm)

coef(lm, s=cvlm$lambda.min)
coef(lm, s=cvlm$lambda.1se)

```

```{r All Cohorts Combined}
#everyone, irrespective of when they joined

prog_survival = prog
paste("There are", length(unique(prog$PERSON_ID)), "individuals in the dataset")

prog_survival$year_month <- (as.integer(prog_survival$YEAR)%%2009)*12+as.integer(prog_survival$MONTH)

prog_survival$od_year_month <- (as.integer(prog_survival$OVERDOSE_YEAR)%%2009)*12+as.integer(prog_survival$OVERDOSE_MONTH)

prog_survival = prog_survival %>% group_by(PERSON_ID) %>% mutate(min_yearmonth=min(year_month))

survival_data_all = prog_survival %>% group_by(PERSON_ID) %>% summarise(time_yearmonth = max(year_month), 
                                                      od_time = max(od_year_month))
survival_data_all = survival_data_all %>% mutate(status = if_else(is.na(od_time), 0, 1))
survival_data_all = survival_data_all %>% mutate(time = if_else(is.na(od_time), time_yearmonth, od_time))
survival_data_all = survival_data_all %>% select(PERSON_ID, status, time)
survival_data_all = merge(survival_data_all, dem, key="PERSON_ID")
survival_data_all = merge(survival_data_all, age_df %>% select(PERSON_ID, age), key="PERSON_ID")

#plot 1
km_all = Surv(survival_data_all$time, survival_data_all$status) %>%
  (function(x) survfit(x ~ 1, data=survival_data_all))(.)
# Kaplan-Meier curve
plot(km_all, xlab= "Months",ylab="P(survive)", mark.time=T)
km_all

#plot 2 (by gender)
km_all_gender = survfit(Surv(survival_data_all$time, survival_data_all$status) ~ gender, data=survival_data_all)
plot(km_all_gender,
     col=c(1:3), mark.time = T); legend("bottomleft", c("Female","Male", "No Data & Other"), col=1:3, lty=c(1,1))
km_all_gender

#analysis by age
km_all_age = survfit(Surv(survival_data_all$time, survival_data_all$status) ~ age<45, data=survival_data_all)
km_all_age

#didn't make sense to plot this.. so just showing output
km_all_race = survfit(Surv(survival_data_all$time, survival_data_all$status) ~ race, data=survival_data_all)
km_all_race

```

```{r All cohorts combined cox}

### Cox model
cm_all = Surv(survival_data_all$time, survival_data_all$status) %>%
  (function(x) coxph(x ~ age + gender, data=survival_data_all))(.)
cm_all

#for all cohorts, being male increases hazard (coefficient)
#for all cohorts, men have 96% greater hazard compared to women??
#this is a statistically significant difference

#controlling for gender, age increases hazard (coefficient)
#1 year increase in age increases hazard by 2.4% controlling for gender??
#this is statistically significant and makes sense

### Regularized Cox model
cox_data_all = survival_data_all %>% select(-time, -status, -PERSON_ID) %>% as.data.frame() %>% as.matrix()
cox_data_all = cox_data_all %>% dummy_cols(c("gender", "race"))
cox_data_all = cox_data_all %>% select(-gender, -race) %>% as.data.frame() %>% as.matrix()

lm_all = glmnet(cox_data_all, Surv(survival_data_all$time, survival_data_all$status), family="cox")
plot(lm)

#How to choose s? Consider sparsity you want with cross-validation
cvlm_all = cv.glmnet(cox_data_all, Surv(survival_data_all$time, survival_data_all$status), family="cox")
plot(cvlm_all)

coef(lm_all, s=cvlm_all$lambda.min)
coef(lm_all, s=cvlm_all$lambda.1se)


```

